/* unofficial gameplaySP kai
 *
 * Copyright (C) 2006 Exophase <exophase@gmail.com>
 * Copyright (C) 2007 takka <takka@tfact.net>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#ifndef MESSAGE_H
#define MESSAGE_H

enum MSG
{

  MSG_RETURN_MENU,

  MSG_MENU_DATE_FMT_0,
  MSG_MENU_DATE_FMT_1,
  MSG_MENU_DATE_FMT_2,

  MSG_MAIN_MENU_TITLE,

  MSG_MAIN_MENU_0,
  MSG_MAIN_MENU_1,
  MSG_MAIN_MENU_2,
  MSG_MAIN_MENU_3,
  MSG_MAIN_MENU_4,
  MSG_MAIN_MENU_5,
  MSG_MAIN_MENU_6,
  MSG_MAIN_MENU_7,
  MSG_MAIN_MENU_8,
  MSG_MAIN_MENU_9,
  MSG_MAIN_MENU_10,
  MSG_MAIN_MENU_11,

  MSG_MAIN_MENU_HELP_0,
  MSG_MAIN_MENU_HELP_1,
  MSG_MAIN_MENU_HELP_2,
  MSG_MAIN_MENU_HELP_3,
  MSG_MAIN_MENU_HELP_4,
  MSG_MAIN_MENU_HELP_5,
  MSG_MAIN_MENU_HELP_6,
  MSG_MAIN_MENU_HELP_7,
  MSG_MAIN_MENU_HELP_8,
  MSG_MAIN_MENU_HELP_9,
  MSG_MAIN_MENU_HELP_10,
  MSG_MAIN_MENU_HELP_11,

  MSG_OPTION_MENU_TITLE,

  MSG_OPTION_MENU_0,
  MSG_OPTION_MENU_1,
  MSG_OPTION_MENU_2,
  MSG_OPTION_MENU_3,
  MSG_OPTION_MENU_4,
  MSG_OPTION_MENU_5,
  MSG_OPTION_MENU_6,
  MSG_OPTION_MENU_7,
  MSG_OPTION_MENU_8,
  MSG_OPTION_MENU_9,

  MSG_OPTION_MENU_HELP_0,
  MSG_OPTION_MENU_HELP_1,
  MSG_OPTION_MENU_HELP_2,
  MSG_OPTION_MENU_HELP_3,
  MSG_OPTION_MENU_HELP_4,
  MSG_OPTION_MENU_HELP_5,
  MSG_OPTION_MENU_HELP_6,
  MSG_OPTION_MENU_HELP_7,
  MSG_OPTION_MENU_HELP_8,
  MSG_OPTION_MENU_HELP_9,

  MSG_STATE_MENU_DATE_FMT_0,
  MSG_STATE_MENU_DATE_FMT_1,
  MSG_STATE_MENU_DATE_FMT_2,

  MSG_STATE_MENU_DATE_NONE_0,
  MSG_STATE_MENU_DATE_NONE_1,
  MSG_STATE_MENU_DATE_NONE_2,

  MSG_STATE_MENU_STATE_NONE,

  MSG_STATE_MENU_TITLE,

  MSG_STATE_MENU_0,
  MSG_STATE_MENU_1,
  MSG_STATE_MENU_2,
  MSG_STATE_MENU_3,
  MSG_STATE_MENU_4,

  MSG_STATE_MENU_HELP_0,
  MSG_STATE_MENU_HELP_1,
  MSG_STATE_MENU_HELP_2,
  MSG_STATE_MENU_HELP_3,
  MSG_STATE_MENU_HELP_4,

  MSG_PAD_MENU_TITLE,

  MSG_PAD_MENU_0,
  MSG_PAD_MENU_1,
  MSG_PAD_MENU_2,
  MSG_PAD_MENU_3,
  MSG_PAD_MENU_4,
  MSG_PAD_MENU_5,
  MSG_PAD_MENU_6,
  MSG_PAD_MENU_7,
  MSG_PAD_MENU_8,
  MSG_PAD_MENU_9,
  MSG_PAD_MENU_10,
  MSG_PAD_MENU_11,
  MSG_PAD_MENU_12,

  MSG_PAD_MENU_HELP_0,

  MSG_PAD_MENU_CFG_0,
  MSG_PAD_MENU_CFG_1,
  MSG_PAD_MENU_CFG_2,
  MSG_PAD_MENU_CFG_3,
  MSG_PAD_MENU_CFG_4,
  MSG_PAD_MENU_CFG_5,
  MSG_PAD_MENU_CFG_6,
  MSG_PAD_MENU_CFG_7,
  MSG_PAD_MENU_CFG_8,
  MSG_PAD_MENU_CFG_9,
  MSG_PAD_MENU_CFG_10,
  MSG_PAD_MENU_CFG_11,
  MSG_PAD_MENU_CFG_12,
  MSG_PAD_MENU_CFG_13,
  MSG_PAD_MENU_CFG_14,
  MSG_PAD_MENU_CFG_15,
  MSG_PAD_MENU_CFG_16,
  MSG_PAD_MENU_CFG_17,
  MSG_PAD_MENU_CFG_18,
  MSG_PAD_MENU_CFG_19,

  MSG_PAD_MENU_CFG_HELP_0,
  MSG_PAD_MENU_CFG_HELP_1,
  MSG_PAD_MENU_CFG_HELP_2,
  MSG_PAD_MENU_CFG_HELP_3,
  MSG_PAD_MENU_CFG_HELP_4,
  MSG_PAD_MENU_CFG_HELP_5,
  MSG_PAD_MENU_CFG_HELP_6,
  MSG_PAD_MENU_CFG_HELP_7,
  MSG_PAD_MENU_CFG_HELP_8,
  MSG_PAD_MENU_CFG_HELP_9,
  MSG_PAD_MENU_CFG_HELP_10,
  MSG_PAD_MENU_CFG_HELP_11,
  MSG_PAD_MENU_CFG_HELP_12,
  MSG_PAD_MENU_CFG_HELP_13,
  MSG_PAD_MENU_CFG_HELP_14,
  MSG_PAD_MENU_CFG_HELP_15,
  MSG_PAD_MENU_CFG_HELP_16,
  MSG_PAD_MENU_CFG_HELP_17,
  MSG_PAD_MENU_CFG_HELP_18,
  MSG_PAD_MENU_CFG_HELP_19,

  MSG_A_PAD_MENU_TITLE,

  MSG_A_PAD_MENU_0,
  MSG_A_PAD_MENU_1,
  MSG_A_PAD_MENU_2,
  MSG_A_PAD_MENU_3,
  MSG_A_PAD_MENU_4,
  MSG_A_PAD_MENU_5,
  MSG_A_PAD_MENU_6,

  MSG_A_PAD_MENU_HELP_0,
  MSG_A_PAD_MENU_HELP_1,
  MSG_A_PAD_MENU_HELP_2,

  MSG_CHEAT_MENU_TITLE,

  MSG_CHEAT_MENU_NON_LOAD,
  MSG_CHEAT_MENU_0,
  MSG_CHEAT_MENU_1,
  MSG_CHEAT_MENU_2,

  MSG_CHEAT_MENU_HELP_0,
  MSG_CHEAT_MENU_HELP_1,
  MSG_CHEAT_MENU_HELP_2,

  MSG_NON_LOAD_GAME,

  MSG_DAYW_0,
  MSG_DAYW_1,
  MSG_DAYW_2,
  MSG_DAYW_3,
  MSG_DAYW_4,
  MSG_DAYW_5,
  MSG_DAYW_6,

  MSG_YES,
  MSG_NO,

  MSG_ENABLED,
  MSG_DISABLED,

  MSG_SCN_UNSCALED,
  MSG_SCN_SCALED_X15_GU,
  MSG_SCN_SCALED_X15_SW,
  MSG_SCN_SCALED_USER,

  MSG_FS_AUTO,
  MSG_FS_MANUAL,
  MSG_FS_OFF,

  MSG_FS_UNIFORM,
  MSG_FS_RANDOM,

  MSG_BK_EXITONLY,
  MSG_BK_AUTO,

  MSG_SS_FMT_0,
  MSG_SS_FMT_1,
  MSG_SS_FMT_2,

  MSG_ERR_BIOS_NONE1,
  MSG_ERR_BIOS_NONE2,
  MSG_ERR_BIOS_HASH1,
  MSG_ERR_BIOS_HASH2,

  MSG_END
};

char msg[MSG_END][512];

#endif /* MESSAGE_H */
